[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
sea-orm = { version = "1.1.3", features = ["macros", "sqlx-postgres"] }
serde = { version = "1.0", features = ["derive"] }
