services:
  sms_backend:
    container_name: sms_backend
    image: bracyw/rust-sms-backend
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:password@sms_db:5432/sms_db
    ports:
      - "8000:8000"
    depends_on:
      - sms_db
  sms_db:
    container_name: sms_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sms_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}