services:
  sms_backend:
    container_name: sms_backend
    image: bracyw/rust-sms-backend
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@sms_db:5432/sms_db
      RUST_BACKTRACE: 1
      SERVER_ADDRESS: "0.0.0.0:4201"  # Bind to all interfaces on port 4201
    ports:
      - "4201:4201"
    depends_on:
      - sms_db

  sms_db:
    container_name: sms_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sms_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
